### ISSUE TITLE
楼主下次发布更新

### ISSUE THREAD

**Issue by chuxue2005** [nbagonet/wxa-compressor#1]
欢迎将更新版本发布在这里：http://www.wxapp-union.com/forum.php?mod=forumdisplay&fid=37

**Comment by nbagonet** [comment]
@chuxue2005 可以直接转过去，当然如果可以署名就更让人开心了：）

**Comment by chuxue2005** [comment]
我刚转了你的第一个版本，觉得这个工具潜力很大，注名了
